# Generated by Django 4.0.4 on 2022-10-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_doctor',
        ),
    ]
