# Generated by Django 4.1.2 on 2022-10-09 08:33

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_note_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note", old_name="content", new_name="badania",
        ),
        migrations.RenameField(model_name="note", old_name="title", new_name="name",),
        migrations.AddField(
            model_name="note",
            name="lekarstwa",
            field=django_cryptography.fields.encrypt(
                models.TextField(default=4234, max_length=5000)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="recepty",
            field=django_cryptography.fields.encrypt(
                models.TextField(default=43, max_length=5000)
            ),
            preserve_default=False,
        ),
    ]
