# Generated by Django 4.1.2 on 2022-10-09 10:45

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_rename_content_note_badania_rename_title_note_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="skierowanie",
            field=django_cryptography.fields.encrypt(
                models.TextField(default=342, max_length=5000)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="wizyta",
            field=django_cryptography.fields.encrypt(
                models.TextField(default=43, max_length=5000)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="zalecenia",
            field=django_cryptography.fields.encrypt(
                models.TextField(default=23, max_length=5000)
            ),
            preserve_default=False,
        ),
    ]
